# -*- coding: utf-8 -*-
"""NDBBGT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1opYl8D2YsQ8qixArITffCsQBPUqAuhzF
"""

# Cài đặt các thư viện cần thiết
!pip install ultralytics

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from ultralytics import YOLO
import cv2
import os
import yaml
from google.colab import drive
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
from tensorflow.keras.callbacks import EarlyStopping

# Tắt GPU, chạy trên CPU
#tf.config.set_visible_devices([], 'GPU')  # Chỉ dùng CPU

# Mount Google Drive
drive.mount('/content/drive')

# --- STEP 1 ---
# Đường dẫn dữ liệu YOLOv8
dataset_path = "/content/drive/MyDrive/DeepLearning/dataset"
yaml_path = os.path.join(dataset_path, "data.yaml")

# Đọc file data.yaml
with open(yaml_path, "r") as f:
    data = yaml.safe_load(f)
    classes = data.get("names", [])
NUM_CLASSES = len(classes)
print(f"✅ Step 1: Problem Understanding - Số lớp: {NUM_CLASSES}, Danh sách lớp: {classes}")

# --- STEP 2: DATA UNDERSTANDING ---
def check_data(split):
    img_dir = os.path.join(dataset_path, split, "images")
    label_dir = os.path.join(dataset_path, split, "labels")
    img_count = len(os.listdir(img_dir))
    label_count = len(os.listdir(label_dir))
    print(f"📂 {split}: {img_count} ảnh, {label_count} nhãn")
    return img_count, label_count

print("\n✅ Step 2: Data Understanding")
for split in ["train", "valid", "test"]:
    check_data(split)

# Kiểm tra phân bố lớp
def analyze_labels(split):
    label_dir = os.path.join(dataset_path, split, "labels")
    label_files = os.listdir(label_dir)
    class_counts = np.zeros(NUM_CLASSES)
    for label_file in label_files:
        label_path = os.path.join(label_dir, label_file)
        with open(label_path, "r") as f:
            lines = f.readlines()
            if lines:
                class_id = int(lines[0].split()[0])
                class_counts[class_id] += 1
    return class_counts

train_counts = analyze_labels("train")
print(f"   - Phân bố lớp trong train: {train_counts}")

# --- STEP 3: FEATURE UNDERSTANDING (EDA) ---
plt.figure(figsize=(10, 5))
plt.bar(range(NUM_CLASSES), train_counts, tick_label=classes)
plt.title("Phân bố lớp trong tập train")
plt.xlabel("Lớp")
plt.ylabel("Số lượng")
plt.xticks(rotation=45)
plt.show()

sample_img_path = os.path.join(dataset_path, "train", "images", os.listdir(os.path.join(dataset_path, "train", "images"))[0])
sample_img = cv2.imread(sample_img_path)
sample_img = cv2.cvtColor(sample_img, cv2.COLOR_BGR2RGB)
plt.imshow(sample_img)
plt.title("Ảnh mẫu từ tập train")
plt.axis('off')
plt.show()

# --- STEP 4 & 5: FEATURE ENGINEERING ---
IMG_SIZE = (32, 32)
BATCH_SIZE = 16

def custom_generator(split, batch_size=BATCH_SIZE):
    img_dir = os.path.join(dataset_path, split, "images")
    label_dir = os.path.join(dataset_path, split, "labels")
    img_files = os.listdir(img_dir)

    # Tạo danh sách ảnh theo lớp để cân bằng
    class_files = [[] for _ in range(NUM_CLASSES)]
    for img_file in img_files:
        label_file = img_file.replace(".jpg", ".txt")
        label_path = os.path.join(label_dir, label_file)
        if os.path.exists(label_path):
            with open(label_path, "r") as f:
                line = f.readline().strip()
                if line:
                    class_id = int(line.split()[0])
                    class_files[class_id].append(img_file)

    # Số mẫu tối đa của lớp lớn nhất
    max_samples = max(len(files) for files in class_files if files)

    while True:
        X_batch, y_batch = [], []
        # Lấy mẫu ngẫu nhiên từ mỗi lớp
        for class_id in range(NUM_CLASSES):
            if not class_files[class_id]:
                continue
            # Lặp lại hoặc lấy mẫu ngẫu nhiên để đủ max_samples
            selected_files = np.random.choice(class_files[class_id],
                                           min(batch_size // NUM_CLASSES, len(class_files[class_id])),
                                           replace=False)
            for img_file in selected_files:
                img_path = os.path.join(img_dir, img_file)
                label_path = os.path.join(label_dir, img_file.replace(".jpg", ".txt"))

                img = cv2.imread(img_path)
                if img is None:
                    print(f"Warning: Failed to load image {img_path}")
                    continue
                img = cv2.resize(img, IMG_SIZE)
                img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) / 255.0

                with open(label_path, "r") as f:
                    line = f.readline().strip()
                    if line:
                        class_id = int(line.split()[0])
                        y_onehot = np.zeros(NUM_CLASSES)
                        y_onehot[class_id] = 1
                        X_batch.append(img)
                        y_batch.append(y_onehot)

        if len(X_batch) > 0:
            X_batch = np.array(X_batch)
            y_batch = np.array(y_batch)
            print(f"Generated batch for {split}: {X_batch.shape}, {y_batch.shape}")
            yield X_batch, y_batch
        else:
            print(f"Warning: Empty batch in {split}")

# Tính số bước để dùng hết tập train
train_steps = (6390 + BATCH_SIZE - 1) // BATCH_SIZE  # 400 với BATCH_SIZE=16
valid_steps = (433 + BATCH_SIZE - 1) // BATCH_SIZE   # 28
test_steps = (317 + BATCH_SIZE - 1) // BATCH_SIZE    # 20
print(f"✅ Step 4 & 5: Feature Engineering & Dataset Partition")
print(f"   - Train steps: {train_steps}, Valid steps: {valid_steps}, Test steps: {test_steps}")
print(f"   - Tổng ảnh train được xử lý mỗi epoch: {train_steps * BATCH_SIZE}")

# --- STEP 6: DATA MODELLING ---
# CNN
cnn_model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(NUM_CLASSES, activation='softmax')
])
cnn_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Huấn luyện CNN
early_stopping = EarlyStopping(monitor='val_loss', patience=2, restore_best_weights=True)
try:
    cnn_history = cnn_model.fit(
        custom_generator("train"),
        steps_per_epoch=train_steps,
        epochs=10,
        validation_data=custom_generator("valid"),
        validation_steps=valid_steps,
        callbacks=[early_stopping],
        verbose=1
    )
    print("✅ CNN training completed successfully")
except Exception as e:
    print(f"Error during CNN training: {e}")
    raise

# YOLOv8
yolo_model = YOLO('yolov8n.pt')
try:
    yolo_model.train(data=yaml_path, epochs=15, imgsz=64, batch=16)
    print("✅ YOLOv8 training completed successfully")
except Exception as e:
    print(f"Error during YOLOv8 training: {e}")

# --- STEP 7: DATA EVALUATION ---
# CNN
test_gen = custom_generator("test")
y_test_pred_all, y_test_true_all = [], []
for step in range(test_steps):
    try:
        X_batch, y_batch = next(test_gen)
        if len(X_batch) > 0:
            y_pred_batch = cnn_model.predict(X_batch, verbose=0)
            y_test_pred_all.extend(y_pred_batch)
            y_test_true_all.extend(y_batch)
            print(f"Processed batch {step+1}/{test_steps}")
        else:
            print(f"Empty batch at step {step+1}")
    except Exception as e:
        print(f"Error in test generator at step {step+1}: {e}")
        break

if len(y_test_pred_all) > 0:
    y_test_pred_all = np.array(y_test_pred_all)
    y_test_true_all = np.array(y_test_true_all)
    y_test_pred_labels = np.argmax(y_test_pred_all, axis=1)
    y_test_true_labels = np.argmax(y_test_true_all, axis=1)
    print("\n✅ Step 7: Data Evaluation - CNN")
    print(classification_report(y_test_true_labels, y_test_pred_labels, target_names=classes))
    cm = confusion_matrix(y_test_true_labels, y_test_pred_labels)
    sns.heatmap(cm, annot=True, fmt='d', xticklabels=classes, yticklabels=classes)
    plt.title("Confusion Matrix - CNN")
    plt.show()
else:
    print("No valid test data collected for evaluation")

# YOLOv8
print("   - YOLOv8: Xem metrics (mAP) trong log huấn luyện")

# --- STEP 8: HYPER-PARAMETER TUNING ---
# CNN
try:
    cnn_model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001), loss='categorical_crossentropy', metrics=['accuracy'])
    cnn_history_tuned = cnn_model.fit(
        custom_generator("train"),
        steps_per_epoch=train_steps,
        epochs=5,
        validation_data=custom_generator("valid"),
        validation_steps=valid_steps,
        verbose=1
    )
    print("✅ CNN tuning completed successfully")
except Exception as e:
    print(f"Error during CNN tuning: {e}")

# YOLOv8
try:
    yolo_model.train(data=yaml_path, epochs=10, imgsz=64, batch=16, lr0=0.001)
    print("✅ YOLOv8 tuning completed successfully")
except Exception as e:
    print(f"Error during YOLOv8 tuning: {e}")

# --- STEP 9: BUILD THE PIPELINE ---
def preprocess_image(img_path):
    img = cv2.imread(img_path)
    img = cv2.resize(img, IMG_SIZE)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) / 255.0
    return np.expand_dims(img, axis=0)

cnn_model.save('/content/drive/MyDrive/DeepLearning/traffic_sign_cnn_best.h5')
yolo_model.save('/content/drive/MyDrive/DeepLearning/traffic_sign_yolov8_best.pt')

# --- STEP 10: CONCLUSION ---
print("\n✅ Step 10: Conclusion")
print("   - CNN: Phân loại trên toàn bộ tập train với generator cân bằng.")
print("   - YOLOv8: Phát hiện và gắn nhãn trên toàn bộ tập train.")
print("   - Hạn chế: Chạy trên CPU, thời gian lâu hơn.")
print("   - Hướng phát triển: Dùng GPU mạnh hơn nếu cần tốc độ.")

# Hiển thị kết quả mẫu
test_img_dir = os.path.join(dataset_path, "test", "images")
test_images = os.listdir(test_img_dir)
random_indices = np.random.randint(0, len(test_images), 5)

plt.figure(figsize=(15, 10))
for i, idx in enumerate(random_indices):
    img_path = os.path.join(test_img_dir, test_images[idx])
    img = cv2.imread(img_path)
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # CNN prediction
    cnn_input = preprocess_image(img_path)
    cnn_pred = cnn_model.predict(cnn_input)
    cnn_label = classes[np.argmax(cnn_pred)]

    # YOLOv8 prediction
    yolo_results = yolo_model.predict(img_path, conf=0.25, iou=0.45)
    yolo_img = yolo_results[0].plot(labels=True, boxes=True)

    plt.subplot(2, 5, i+1)
    plt.imshow(img_rgb)
    plt.title(f"CNN: {cnn_label}")
    plt.axis('off')

    plt.subplot(2, 5, i+6)
    plt.imshow(yolo_img)
    plt.title("YOLOv8")
    plt.axis('off')

plt.tight_layout()
plt.show()